version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lib-db
    environment:
      POSTGRES_USER: libuser
      POSTGRES_PASSWORD: libpass
      POSTGRES_DB: libdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  backend:
    build: ./backend
    container_name: lib-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: libdb
      DB_USER: libuser
      DB_PASSWORD: libpass
    depends_on:
      - db
    networks:
      - backend-net

  adminer:
    image: adminer:4
    container_name: lib-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - backend-net

  frontend:
    build: ./frontend
    container_name: lib-frontend
    networks:
      - backend-net

  reverse-proxy:
    build: ./reverse-proxy   
    container_name: lib-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      - backend-net

volumes:
  db_data:

networks:
  backend-net:
